[package]
name = "adele-gui"
version = "0.1.0"
authors = ["Trevor Merrifield <trevorm42@gmail.com>"]

[dependencies]
conrod = { git = "https://github.com/PistonDevelopers/conrod.git", rev = "0a6d44d" }
piston_window = "0.51.1"
find_folder = "*"
